sim:
  start: 0.0
  stop: 0.5
  seed: 20001
  threads: 1
  check_geo: false
  output_filename: "0.5s_20001_F18_10MBq_0_0_0" #Duration_seed_Isotope1_MBq_offset_Isotope2_MBq_offset

digitizer:
  energy_window_keV: [100, 2000]

phantom:
  include_f18: true
  f18_offset_mm: [0, 0, 0]
  f18_activity_bq: 10.0e6

  include_Mn52: false
  Mn52_offset_mm: [45.0, 0, 0]
  Mn52_activity_bq: 1.0e6
